### ISSUE TITLE
Not working on SubFixture?

### ISSUE THREAD

**Issue by TomyVertigo** [hossimo/GMA3Plugins#3]
Hello,

does this function not work on SubFixtures?
![image](https://user-images.githubusercontent.com/63294196/78690211-75fd2100-78f7-11ea-9441-2acded160c64.png)

If I try to run it it just throws out. 

Thank you.
Tomy

**Comment by hossimo** [comment]
I'm guessing you're using Random Select, I just checked and unfortunately it does not currently work with sub fixtures. The API that I'm using is called `GetSubfixture` and I pass it the patch index of a fixture and it gives me back the FixtureID (FID) for the fixture. Technically sub fixtures look like they don't store a FID, but they drive it based on how deep it is in the tree.

So for example a Grouping fixture with FID 100 and it's Child fixtures 101 thru 112 does work, since all of the children fixtures have a FID, but something like an Alien Pix doesn't because since the sub fixtures don't include FID's in the patch.

I'm sure there is a simple way for me to fix this but I'll have to look into the APIs and see if I can find something that will help or perhaps walk up the tree myself and figure out what the FID should be. 

I'll take a look, might take a bit since there is currently no documentation for the APIs and I'm kind of working blind but It should be doable.

**Comment by hossimo** [comment]
I think #5, [Release 7](https://github.com/hossimo/GMA3Plugins/releases/tag/1.1.3.2.1) or, the head of the master should solve the issue.

I couldn't find anything official to calculate the SubFixtureID so I made something that seems to work.

Let me know.

**Comment by TomyVertigo** [comment]
Man. It works! 
You're a genius. R.E.S.P.E.C.T.
